# Introduction to Python



[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/EleonoraAiello/AIM23-24/blob/main/IntroToPython.ipynb)
    

In [1]:
# 'generic import' of math module
import math
math.sqrt(25)

# import functions at once
from math import cos, floor

# define an alias
import pandas as pd


## Data Types

Python is a dynamically typed language. This means that the type of each variable is not fixed, but it is rather determined by the execution flow of your program. The major data types in Python are: *integers*, *floating points*, *lists*, *tuples*, *dictionaries*, *sets*, *strings* and *booleans*.


In [2]:
# determine the type of an object
type(2)         # returns 'int'
type(2.0)       # returns 'float'
type('two')     # returns 'str'
type(True)      # returns 'bool'
type(None)      # returns 'NoneType'

# convert an object to a given type
float(2)
int(2.9)
str(2.9)


True

## Math

In [3]:
# basic operations
10 + 4          # add (returns 14)
10 - 4          # subtract (returns 6)
10 * 4          # multiply (returns 40)
10 ** 4         # exponent (returns 10000)
5 % 4           # modulo (returns 1) - computes the remainder
10 / 4          # divide (returns 2.5)
10 // 4         # floor division (returns 2)

2

In [7]:
# here we 'alias' the NumPy library with the alias 'np'
import numpy as np

# Create a rank 1 array
a = np.array([1, 2, 3])
print("Type of the array:", type(a))
print("Rank of the array:", a.ndim)
print("Shape of the array:", a.shape)
print("The array itself:", a)

# access / change an element of the array
a[0] = 5
print("Now the array has changed:", a)  


Type of the array: <class 'numpy.ndarray'>
Rank of the array: 1
Shape of the array: (3,)
The array itself: [1 2 3]
Now the array has changed: [5 2 3]


In [17]:
# Create a rank 2 array
nested_list = [[1,2,3],
               [4,5,6]]
b = np.array(nested_list)
print("The array itself:\n", b)
print("Rank of the array:", b.ndim)
print("Shape of the array:", b.shape)

# access / change individual elements of the array
b[0,0] = 5
print("Now the array has changed:\n", b)



The array itself:
 [[1 2 3]
 [4 5 6]]
Rank of the array: 2
Shape of the array: (2, 3)
Now the array has changed:
 [[5 2 3]
 [4 5 6]]


In [18]:
# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

#accessing rows of an array
row_r1 = a[1, :]    # Rank 1 view of the second row of a  
row_r2 = a[1:2, :]  # Rank 2 view of the second row of a

# We can make the same distinction when accessing columns of an array:
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
# Use slicing to extract the subarray consisting of the first 2 rows
# and the last 3 columns 

b = a[:2, 1:]
print(b)

# Mutate one element from each row of a using the indices in b
# This is useful when the same operation must be applied to more cells!
a[:2, 1:] += 10
print(a)

[[2 3 4]
 [6 7 8]]
[[ 1 12 13 14]
 [ 5 16 17 18]
 [ 9 10 11 12]]


In [5]:
# create a string
s = 'I like you'

# examine a string (you can see them as python lists of characters!)
s[0]                # returns 'I'
len(s)              # returns 10


# string slicing is like list slicing
s[:6]               # returns 'I like'
s[7:]               # returns 'you'
s[-1]               # returns 'u'

# basic string methods (does not modify the original string)
s.startswith('I')   # returns True
s.endswith('you')   # returns True
s.find('like')      # returns index of first occurrence (2), but doesn't support regex
s.find('hate')      # returns -1 since not found
s.replace('like', 'love')    # replaces all instances of 'like' with 'love'

# split a string into a list of substrings separated by a delimiter
s.split(' ')        # returns ['I', 'like', 'you']
s.split()           # equivalent (since space is the default delimiter)
s2 = 'a, an, the'
s2.split(',')       # returns ['a', ' an', ' the']

# concatenate strings
s3 = 'The meaning of life is'
s4 = '42'
s3 + ' ' + s4       # returns 'The meaning of life is 42'


first line
second line
first line\nfirst line


## Lists

Lists are tha main python objects to encapsulate a sequence. Lists can be ordered, they are iterable (i.e. you can loop through lists), they are mutable (i.e. you can change their content) and, most importantly, they can contain multiple data types!

In [ ]:
# create an empty list (two ways)
#loc

empty_list = []
empty_list = list()

# create a list

elements = ['Hand', 'BreastMRI', 'ChestCT']

# examine a list
elements[0]     # print element 0 ('Hand')
len(elements)   # returns the length (3)

# modify a list (does not return the list)
elements.append('HeadCT')                 # append element to end
elements.extend(['Abdomen', 'CXR'])  # append multiple elements to end
elements.remove('BreastMRI')                 # search for the first instance of 'BreastMRI' and removes it
elements.pop(0)                         # remove element 0 and return it
elements[0] = 'HeadCT'                  # replace element 0

# find elements in a list
elements.count('HeadCT')      # counts the number of instances
elements.index('Abdomen')     # returns index of first instance

# list slicing [start:end:step]

weekdays[0]         # element 0
weekdays[0:3]       # elements 0, 1, 2
weekdays[:3]        # elements 0, 1, 2 (default start is 0)
weekdays[3:]        # elements 3, 4
weekdays[-1]        # last element (element 4)
weekdays[::2]       # every 2nd element (0, 2, 4)
weekdays[::-1]      # backwards (4, 3, 2, 1, 0)


# sort a list in place (modifies but does not return the list)
elements.sort()

## Comparison and Boolean operators

In [3]:
# assignment statement
x = 5

# comparisons (these return True)
x > 3
x >= 3
x != 3
x == 5

# boolean operations (these return True)
5 > 3 and 6 > 3
5 > 3 or 5 < 3

(False or ((not False) and True))     # evaluation order: not, and, or

True

## Conditional statements

In [4]:
# if statement
if x > 0:
    print('positive')

# if/else statement
if x > 0:
    print('positive')
else:
    print('zero or negative')

# if/elif/else statement
if x > 0:
    print('positive')
elif x == 0:
    print('zero')
else:
    print('negative')


positive
positive
positive


## For loop

In [24]:
# range returns a sequence 
range(0, 3)     # returns [0, 1, 2]: includes start value but excludes stop value
range(3)        # equivalent: default start value is 0
range(0, 5, 2)  # returns [0, 2, 4]: third argument is the step value

# for loop to create a list of cubes
nums = [1, 2, 3, 4, 5]
cubes = []
for num in nums:
    cubes.append(num**3)

# for loop to create a list of cubes of even numbers
cubes_of_even = []
for num in nums:
    if num % 2 == 0:
        cubes_of_even.append(num**3)

# for loop to cube even numbers and square odd numbers
cubes_and_squares = []
for num in nums:
    if num % 2 == 0:
        cubes_and_squares.append(num**3)
    else:
        cubes_and_squares.append(num**2)


0 mon
1 tues
2 wed
3 thurs
4 fri
0 mon
1 tues
2 wed
3 thurs
4 fri
mon
wed
thurs
fri
Count is 0
Count is 1
Count is 2
Count is 3
Count is 4
Count is 5, not in the while loop anymore.



# while loop

In [ ]:

count = 0
while count < 5:
    print(f'Count is {count}')
    count += 1    # equivalent to 'count = count + 1', there is no '++' in python
print(f"Count is {count}, not in the while loop anymore.")

## Functions

In [28]:
# define a function with no arguments and no return values
def print_text():
    print('this is text')

# call the function
print_text()

# define a function with one argument and no return values
def print_this(x):
    print(x)

# call the function
print_this(3)       # prints 3
n = print_this(3)   # prints 3, but doesn't assign 3 to n
                    #   because the function has no return statement
print(n)
# define a function with one argument and one return value
def square_this(x):
    return x**2

# include an optional docstring to describe the effect of a function
# (hover with your mouse on the function name to see the effect of docstrings)
def square_this(x):
    """Return the square of a number."""
    return x**2

# call the function
square_this(3)          # prints 9
var = square_this(3)    # assigns 9 to var, but does not print 9


this is text
3
3
None
